import api from './axios';

export const getKPIs              = ()       => api.get('/manager/kpis');
export const getUsers             = (params) => api.get('/manager/users', { params });
export const createUser           = (data)   => api.post('/manager/users', data);
export const updateUser           = (id, data) => api.put(`/manager/users/${id}`, data);
export const updateUserRole       = (id, role) => api.patch(`/manager/users/${id}/role`, { role });
export const deleteUser           = (id)     => api.delete(`/manager/users/${id}`);
export const getAllTickets         = (params) => api.get('/manager/tickets', { params });
export const getTicketDistribution = ()      => api.get('/manager/tickets/distribution');
export const getEscalatedTickets   = ()      => api.get('/manager/tickets/escalated');
export const getTicketTrends       = (days)  => api.get('/manager/analytics/trends', { params: { days } });
export const getCommonIssues       = ()      => api.get('/manager/analytics/common-issues');
export const getResolutionStats    = ()      => api.get('/manager/analytics/resolution-stats');
export const getStaffPerformance   = ()      => api.get('/manager/team/performance');
export const getWorkloadDist       = ()      => api.get('/manager/team/workload');
export const getSlaRules           = ()      => api.get('/manager/sla/rules');
export const updateSlaRule         = (id, d) => api.put(`/manager/sla/rules/${id}`, d);
export const getSlaViolations      = ()      => api.get('/manager/sla/violations');
export const getResolutionTime     = ()      => api.get('/manager/sla/resolution-time');
export const getTicketReport       = (p)     => api.get('/manager/reports/tickets', { params: p });
export const getEmployeeReport     = ()      => api.get('/manager/reports/employees');
export const getClientReport       = ()      => api.get('/manager/reports/clients');
